# Generated by Django 5.2.10 on 2026-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
