# Generated by Django 5.2.10 on 2026-02-22 09:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DeckBuildTask',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('deck_id', models.UUIDField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
