# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.0.2 on 2026-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckbuildtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('BUILDING_DECK', 'Building Deck'),
                    ('CLASSIFYING_DECK_CARDS', 'Classifying Deck Cards'),
                    ('FINDING_REPLACEMENT_CARDS', 'Finding Replacement Cards'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=50,
            ),
        ),
    ]
