# Generated by Django 6.0.2 on 2026-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckbuildtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('BUILDING_DECK', 'Building Deck'),
                    ('CLASSIFYING_DECK_CARDS', 'Classifying Deck Cards'),
                    ('FINDING_REPLACEMENT_CARDS', 'Finding Replacement Cards'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=50,
            ),
        ),
    ]
