# Generated by Django 6.0.2 on 2026-03-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0002_alter_deckbuildtask_status'),
        ('appcards', '0011_deckcard_importance_deckcard_replacement_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckbuildtask',
            name='deck_id',
        ),
        migrations.AddField(
            model_name='deckbuildtask',
            name='deck',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='build_tasks',
                to='appcards.deck',
            ),
        ),
    ]
