# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.0.2 on 2026-03-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0002_alter_deckbuildtask_status'),
        ('appcards', '0011_deckcard_importance_deckcard_replacement_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckbuildtask',
            name='deck_id',
        ),
        migrations.AddField(
            model_name='deckbuildtask',
            name='deck',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='build_tasks',
                to='appcards.deck',
            ),
        ),
    ]
