# Generated by Django 6.0.2 on 2026-03-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0003_remove_deckbuildtask_deck_id_deckbuildtask_deck'),
        ('appcards', '0011_deckcard_importance_deckcard_replacement_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckbuildtask',
            name='deck',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='build_tasks', to='appcards.deck'
            ),
        ),
    ]
