# Generated by Django 6.0.3 on 2026-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0004_alter_deckbuildtask_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckbuildtask',
            name='deck_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deckbuildtask',
            name='n_replacements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deckbuildtask',
            name='n_searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deckbuildtask',
            name='n_total_replacements',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
