# Generated by Django 6.0.3 on 2026-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0005_deckbuildtask_deck_size_deckbuildtask_n_replacements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckbuildtask',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
