# Generated by Django 6.0.3 on 2026-04-18 02:48

import uuid

from django.db import migrations, models

import appai.models.memory


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0006_deckbuildtask_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'related_card_uuids',
                    models.JSONField(blank=True, default=list, validators=[appai.models.memory._validate_uuid_list]),
                ),
            ],
        ),
    ]
