# Generated by Django 6.0.4 on 2026-04-21 12:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0006_deckbuildtask_prompt'),
        ('appcards', '0011_deckcard_importance_deckcard_replacement_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_cards', models.ManyToManyField(blank=True, to='appcards.card')),
            ],
        ),
    ]
