# Generated by Django 6.0.4 on 2026-05-07 09:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appai', '0007_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryMaintenanceReport',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.JSONField()),
            ],
        ),
    ]
