EVERGREEN_KEYWORDS = {
    "Deathtouch",
    "Defender",
    "Double Strike",
    "Enchant",
    "Equip",
    "First Strike",
    "Flash",
    "Flying",
    "Haste",
    "Lifelink",
    "Menace",
    "Protection",
    "Prowess",
    "Reach",
    "Trample",
    "Vigilance",
    "Ward",
}
