EVERGREEN_KEYWORDS = {
    "Deathtouch",
    "Defender",
    "Double Strike",
    "Enchant",
    "Equip",
    "First Strike",
    "Flash",
    "Flying",
    "Haste",
    "Lifelink",
    "Menace",
    "Protection",
    "Prowess",
    "Reach",
    "Trample",
    "Vigilance",
    "Ward",
}

CURRENT_STANDARD_SET_CODES = {
    "FDN",
    "WOE",
    "LCI",
    "MKM",
    "OTJ",
    "BIG",
    "BLB",
    "DSK",
    "DFT",
    "TDM",
    "FIN",
    "EOE",
    "SPM",
}

CARD_TAGS = {
    "Aggro": "Cards that are design to be aggressive and apply early pressure to opponents, often at the cost of long-term value or resilience.",
    "Weenie": "Low-cost, efficiently statted creatures intended to apply early combat pressure.",
    "GoWide": "Cards that generate or support multiple small creatures to overwhelm opponents through board presence.",
    "Burn": "Direct damage effects primarily aimed at reducing an opponent’s life total.",
    "Voltron": "Cards that concentrate power or protection onto a single primary threat to win through combat.",
    "Tempo": "Cards that gain advantage by disrupting the opponent while advancing your board efficiently.",
    "Midrange": "Cards that are effective in the mid-game, often balancing cost and power to adapt to various strategies.",
    "ValueThreat": "Creatures or permanents that provide strong standalone value while also applying pressure.",
    "ETBValue": "Cards that generate value immediately when entering the battlefield.",
    "Grindy": "Cards that provide incremental long-term advantage in extended games.",
    "Toolbox": "Cards that enable flexible answers or silver-bullet style solutions.",
    "Control": "Cards that are designed to manage the game state and neutralise threats, often through disruption or resource denial.",
    "Permission": "Cards that prevent opposing spells or actions from resolving.",
    "BoardControl": "Cards that manage or suppress the opponent’s board development.",
    "Removal": "Flexible answers that eliminate individual opposing threats.",
    "Prison": "Cards that restrict opponents’ actions or limit available resources over time.",
    "Pillowfort": "Defensive effects that discourage or tax opponents from attacking you.",
    "Combo": "Cards that are designed to work together in a synergistic way to create a powerful effect that can often win the game outright.",
    "ComboPiece": "A card that forms part of a synergistic interaction that can generate a powerful or game-winning effect.",
    "InfiniteCombo": "Cards that enable or complete a loop producing unlimited resources or deterministic victory.",
    "AlternateWincon": "Cards that win the game through non-standard victory conditions.",
    "Storm": "Cards that scale significantly with the number of spells cast in a turn.",
    "GraveyardCombo": "Cards that rely on graveyard interactions to assemble powerful synergies.",
    "Aristocrats": "Cards that benefit from sacrificing creatures or exploiting death triggers.",
    "Ramp": "Cards that accelerate mana production to enable casting more powerful spells earlier than normal.",
    "LandRamp": "Effects that accelerate mana by putting additional lands into play.",
    "ManaDork": "Creatures that produce mana to accelerate development.",
    "ManaRock": "Non-creature permanents that generate mana.",
    "Ritual": "Temporary bursts of mana that provide short-term acceleration.",
    "CostReduction": "Cards that reduce the mana cost of spells or abilities.",
    "CardAdvantage": "Cards that provide additional resources or options, often by drawing extra cards or generating other forms of advantage.",
    "DrawEngine": "Repeatable or high-yield effects that generate sustained card advantage.",
    "Cantrip": "Low-cost spells that replace themselves immediately.",
    "Looting": "Effects that draw and discard to improve card selection.",
    "Wheel": "Effects that cause players to discard hands and draw new ones.",
    "Tutor": "Cards that search the library for specific cards.",
    "Recursion": "Effects that return cards from the graveyard to hand, battlefield, or library.",
    "SelfMill": "Cards that intentionally put cards from your library into your graveyard.",
    "Interaction": "Cards that directly interact with opponents’ spells, abilities, or permanents to disrupt their plans.",
    "SpotRemoval": "Single-target answers to creatures or other permanents.",
    "BoardWipe": "Effects that remove multiple permanents at once.",
    "Counterspell": "Spells that directly counter other spells on the stack.",
    "Discard": "Effects that force opponents to discard cards from hand.",
    "GraveyardHate": "Cards that disrupt or neutralize graveyard-based strategies.",
    "ArtifactEnchantmentRemoval": "Effects that specifically answer artifacts or enchantments.",
    "ResourceDenial": "Cards that restrict opponents’ access to resources like mana, cards, or actions.",
    "LandDestruction": "Cards that destroy, exile, or otherwise remove lands.",
    "TaxEffect": "Effects that increase opponents’ costs for spells or actions.",
    "StaxPiece": "Permanents that symmetrically restrict resources but are built around for advantage.",
    "Synergy": "Cards that have enhanced value when combined with specific other cards or strategies.",
    "TokenSynergy": "Cards that create tokens or scale in power based on token presence.",
    "SacrificeOutlet": "Cards that allow repeated or reliable sacrificing of permanents.",
    "Blink": "Effects that exile and return permanents to reuse enter-the-battlefield abilities.",
    "CopyEffect": "Cards that copy spells, abilities, or permanents.",
    "CheatIntoPlay": "Effects that put high-cost cards onto the battlefield without paying full cost.",
    "SpellsMatter": "Cards that reward casting noncreature spells.",
    "LifegainSynergy": "Cards that scale or trigger based on gaining life.",
    "Tribal": "Cards that have enhanced value when combined with specific creature types or tribal synergies.",
    "TribalPayoff": "Cards that reward controlling multiple creatures of a shared type.",
    "TribalEnabler": "Cards that support or enhance a specific creature type strategy.",
}
