# Generated by Django 5.2.10 on 2026-03-01 06:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='appauth.refreshtoken',
            ),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='replaced_by',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replaced_token',
                to='appauth.refreshtoken',
            ),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
