FROM python:3.12-slim

ARG UID=1000
ARG GID=1000

# Create a non-root user matching host UID/GID
RUN groupadd -g ${GID} dev && useradd -m -u ${UID} -g ${GID} -s /bin/bash dev

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 
#     PIP_DISABLE_PIP_VERSION_CHECK=1 \
#     UV_PROJECT_ENVIRONMENT=/workspace/.venv \
#     PATH="/workspace/.venv/bin:$PATH"

# WORKDIR /workspace

# Basic OS deps you’ll want in dev (git for pre-commit hooks, curl for installers, etc.)
RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl ca-certificates build-essential openssh-client iproute2 postgresql-client npm unzip \
    && rm -rf /var/lib/apt/lists/*

