# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.10 on 2026-02-11 06:11

import uuid

from django.db import migrations, models

import appcards.models.card


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_summary', models.TextField(blank=True, null=True)),
                (
                    'subtypes',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
                (
                    'supertypes',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('mana_cost_red', models.IntegerField(default=0)),
                ('mana_cost_blue', models.IntegerField(default=0)),
                ('mana_cost_green', models.IntegerField(default=0)),
                ('mana_cost_white', models.IntegerField(default=0)),
                ('mana_cost_black', models.IntegerField(default=0)),
                ('mana_cost_colorless', models.IntegerField(default=0)),
                ('converted_mana_cost', models.IntegerField(default=0)),
                (
                    'colors',
                    models.JSONField(
                        blank=True, default=list, validators=[appcards.models.card._validate_mana_color_list]
                    ),
                ),
                (
                    'types',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_type_list]),
                ),
                (
                    'rarity',
                    models.CharField(
                        choices=[
                            ('common', 'Common'),
                            ('uncommon', 'Uncommon'),
                            ('rare', 'Rare'),
                            ('mythic', 'Mythic'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'keywords',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
            ],
        ),
    ]
