# Generated by Django 5.2.10 on 2026-01-30 13:55

from django.db import migrations, models

import appcards.models.card


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'name',
                    models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
                ),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_summary', models.TextField(blank=True, null=True)),
                (
                    'subtypes',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
                (
                    'supertypes',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('mana_cost_red', models.IntegerField(default=0)),
                ('mana_cost_blue', models.IntegerField(default=0)),
                ('mana_cost_green', models.IntegerField(default=0)),
                ('mana_cost_white', models.IntegerField(default=0)),
                ('mana_cost_black', models.IntegerField(default=0)),
                ('mana_cost_colorless', models.IntegerField(default=0)),
                ('converted_mana_cost', models.IntegerField(default=0)),
                (
                    'colors',
                    models.JSONField(
                        blank=True, default=list, validators=[appcards.models.card._validate_mana_color_list]
                    ),
                ),
                (
                    'types',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_type_list]),
                ),
                (
                    'rarity',
                    models.CharField(
                        choices=[
                            ('common', 'Common'),
                            ('uncommon', 'Uncommon'),
                            ('rare', 'Rare'),
                            ('mythic', 'Mythic'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'keywords',
                    models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
                ),
            ],
        ),
    ]
