# Generated by Django 5.2.10 on 2026-02-11 06:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('set_code', models.CharField(max_length=10)),
                (
                    'card',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='appcards.card'
                    ),
                ),
            ],
            options={
                'unique_together': {('card', 'set_code')},
            },
        ),
    ]
