# Generated by Django 5.2.10 on 2026-02-19 12:46

import uuid

import django.db.models.deletion
from django.db import migrations, models

import appcards.models.deck


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0002_printing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'set_codes',
                    models.JSONField(blank=True, default=set, validators=[appcards.models.deck._validate_set_str]),
                ),
                ('llm_summary', models.TextField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcards.deck')),
            ],
            options={
                'unique_together': {('deck', 'card')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', through='appcards.DeckCard', to='appcards.card'),
        ),
    ]
