# Generated by Django 5.2.10 on 2026-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0003_deck_deckcard_deck_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='short_llm_summary',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='llm_summary',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
