# Generated by Django 5.2.10 on 2026-02-23 07:04

from django.db import migrations, models

import appcards.models.deck


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0004_deck_short_llm_summary_alter_deck_llm_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='generation_histrory',
            field=models.JSONField(blank=True, default=list, validators=[appcards.models.deck._validate_list_str]),
        ),
    ]
