# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.10 on 2026-02-23 07:52

from django.db import migrations, models

import appcards.models.deck


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0004_deck_short_llm_summary_alter_deck_llm_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='generation_history',
            field=models.JSONField(blank=True, default=list, validators=[appcards.models.deck._validate_list_str]),
        ),
    ]
