# Generated by Django 5.2.10 on 2026-02-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0005_deck_generation_history'),
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_decks',
                to='appuser.user',
            ),
        ),
    ]
