# Generated by Django 5.2.10 on 2026-02-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0006_deck_user'),
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to='appuser.user'
            ),
        ),
    ]
