# Generated by Django 6.0.2 on 2026-03-01 08:54

from django.db import migrations, models

import appcards.models.card


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0007_alter_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list, validators=[appcards.models.card._validate_str_list]),
        ),
    ]
