# Generated by Django 6.0.2 on 2026-03-03 11:51

from django.db import migrations, models

import appcards.models.deck


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0008_card_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.JSONField(blank=True, default=list, validators=[appcards.models.deck._validate_list_str]),
        ),
    ]
