# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.0.2 on 2026-03-03 13:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0009_deck_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeckTheme',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('date', models.DateField(auto_now_add=True)),
                ('theme', models.TextField(max_length=255)),
            ],
        ),
    ]
