# Generated by Django 6.0.2 on 2026-03-03 13:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0009_deck_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeckTheme',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('date', models.DateField(auto_now_add=True)),
                ('theme', models.TextField(max_length=255)),
            ],
        ),
    ]
