# Generated by Django 6.0.2 on 2026-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appcards', '0010_dailydecktheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='importance',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='replacement_cards',
            field=models.ManyToManyField(blank=True, related_name='replacement_for', to='appcards.card'),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
