from uuid import UUID

from appcore.modules.beartype import beartype
from django.forms.models import model_to_dict
from pydantic import BaseModel, Field

from appcards.constants.cards import CARD_TAGS
from appcards.models.card import Card, ManaColorEnum, Rarity, TypeEnum


class CardInfo(BaseModel):
    id: UUID = Field(..., description="The ID of the card")
    name: str = Field(..., description="The name of the card")
    text: str = Field(..., description="The text of the card")
    llm_summary: str | None = Field(None, description="A summary of the card generated by an LLM")
    tags: list[str] = Field(
        default_factory=list,
        description=f"A list of tags that categorise the card based on its attributes and potential roles in a deck. Supported values are: {list(CARD_TAGS.keys())}",
    )
    subtypes: list[str] = Field(default_factory=list, description="The subtypes of the card")
    supertypes: list[str] = Field(default_factory=list, description="The supertypes of the card")
    power: str | None = Field(None, description="The power of the creature")
    toughness: str | None = Field(None, description="The toughness of the creature")
    mana_cost_red: int = Field(..., description="The red mana cost of the card")
    mana_cost_blue: int = Field(..., description="The blue mana cost of the card")
    mana_cost_green: int = Field(..., description="The green mana cost of the card")
    mana_cost_white: int = Field(..., description="The white mana cost of the card")
    mana_cost_black: int = Field(..., description="The black mana cost of the card")
    mana_cost_colorless: int = Field(..., description="The colorless mana cost of the card")
    converted_mana_cost: int = Field(..., description="The converted mana cost of the card")
    colors: list[ManaColorEnum] = Field(
        default_factory=list,
        description=f"The colors of the card, supported values are {list(ManaColorEnum._value2member_map_.keys())}",
    )
    set_codes: list[str] = Field(default_factory=list, description="The set codes of the card")
    types: list[TypeEnum] = Field(
        default_factory=list,
        description=f"The types of the card, supported values are {list(TypeEnum._value2member_map_.keys())}",
    )
    rarity: Rarity = Field(
        ..., description=f"The rarity of the card, supported values are {list(Rarity._value2member_map_.keys())}"
    )
    keywords: list[str] = Field(default_factory=list, description="The keywords of the card")


@beartype
def card_to_info(card: Card) -> CardInfo:
    card_dict = model_to_dict(card, fields=[f.name for f in card._meta.fields])
    card_dict['set_codes'] = [p.set_code for p in card.printings.all()]
    return CardInfo(id=card.id, name=card.name, **card_dict)
