from typing import TYPE_CHECKING
from uuid import UUID

from ninja import Field, Schema
from ninja.errors import HttpError
from pydantic import field_validator

from appcards.models.card import Card
from appcards.models.deck import MAX_DECK_NAME_LENGTH, SHORT_SUMMARY_LENGTH_LIMIT, SUMMARY_LENGTH_LIMIT, Deck
from appcards.modules.card_info import CardInfo


class GetDeckIn(Schema):
    deck_id: UUID = Field(..., description='The unique identifier of the deck to retrieve.')

    if TYPE_CHECKING:
        _deck_cache: Deck

    @property
    def deck(self) -> Deck:
        if not hasattr(self, '_deck_cache'):
            try:
                object.__setattr__(self, '_deck_cache', Deck.objects.select_related('user').get(id=self.deck_id))
            except Deck.DoesNotExist:
                raise HttpError(404, f"Deck with ID {self.deck_id} not found")
        return self._deck_cache


class GetSummaryDeckOut(Schema):
    id: UUID = Field(..., description="The unique identifier of the deck")
    name: str = Field(..., description="The name of the deck")
    short_summary: str | None = Field(None, description="A short summary of the deck generated by an LLM")
    set_codes: list[str] = Field(default_factory=list, description="The set codes of the cards in the deck")
    tags: list[str] = Field(default_factory=list, description="The tags associated with the deck")
    date_updated: str = Field(..., description="The date and time when the deck was last updated, in ISO 8601 format")
    generation_status: str | None = Field(
        None, description="The status of the deck generation process, if the deck is still being constructed"
    )
    generation_task_id: UUID | None = Field(
        None, description="The ID of the deck generation task, if the deck is still being constructed"
    )

    @field_validator('id', mode='after')
    @classmethod
    def validate_id(cls, value: UUID) -> UUID:
        if not Deck.objects.filter(id=value).exists():
            raise RuntimeError('Deck not found')
        return value


class DeckCardInfo(Schema):
    quantity: int = Field(..., description="The quantity of the card in the deck")
    card_info: CardInfo = Field(..., description="The information of the card in the deck")
    role: str | None = Field(None, description="The role of the card in the deck, as classified by an LLM")
    importance: str | None = Field(None, description="The importance of the card in the deck, as classified by an LLM")
    possible_replacements: list[CardInfo] = Field(
        default_factory=list,
        description="A list of possible replacement cards, generated by an LLM, that could be used instead of this card in the deck",
    )


class GetFullDeckOut(Schema):
    id: UUID = Field(..., description="The unique identifier of the deck")
    name: str = Field(..., description="The name of the deck")
    short_summary: str | None = Field(None, description="A short summary of the deck generated by an LLM")
    full_summary: str | None = Field(None, description="A full summary of the deck generated by an LLM")
    set_codes: list[str] = Field(default_factory=list, description="The set codes of the cards in the deck")
    tags: list[str] = Field(default_factory=list, description="The tags associated with the deck")
    date_updated: str = Field(..., description="The date and time when the deck was last updated, in ISO 8601 format")
    cards: list[DeckCardInfo] = Field(
        default_factory=list,
        description="A list of DeckCardInfo objects, each containing the quantity, card information, and possible replacements for a card in the deck",
    )
    creation_status: str | None = Field(
        None, description="The status of the deck creation process, if the deck is still being constructed"
    )

    @field_validator('id', mode='after')
    @classmethod
    def validate_id(cls, value: UUID) -> UUID:
        if not Deck.objects.filter(id=value).exists():
            raise RuntimeError('Deck not found')
        return value

    @field_validator('cards', mode='after')
    @classmethod
    def validate_cards(cls, value: list[DeckCardInfo]) -> list[DeckCardInfo]:
        card_ids = set()
        for card in value:
            if card.quantity < 1:
                raise RuntimeError('Invalid card quantity')
            card_ids.add(card.card_info.id)

        if not Card.objects.filter(id__in=card_ids).count() == len(card_ids):
            raise RuntimeError('One or more cards not found')
        return value


class UpdateDeckIn(Schema):
    name: str | None = Field(
        None, description="The new name of the deck", max_length=MAX_DECK_NAME_LENGTH, min_length=1
    )
    short_summary: str | None = Field(
        None,
        description="A new short summary of the deck generated by an LLM",
        min_length=SHORT_SUMMARY_LENGTH_LIMIT[0],
        max_length=SHORT_SUMMARY_LENGTH_LIMIT[1],
    )
    full_summary: str | None = Field(
        None,
        description="A new full summary of the deck generated by an LLM",
        min_length=SUMMARY_LENGTH_LIMIT[0],
        max_length=SUMMARY_LENGTH_LIMIT[1],
    )
