from typing import TYPE_CHECKING
from uuid import UUID

from appai.models.deck_build import DeckBuildStatus
from ninja import Field, Schema
from ninja.errors import HttpError
from pydantic import field_validator

from appcards.models.card import Card
from appcards.models.deck import Deck
from appcards.modules.card_info import CardInfo


class GetDeckIn(Schema):
    deck_id: UUID = Field(..., description='The unique identifier of the deck to retrieve.')

    if TYPE_CHECKING:
        _deck_cache: Deck

    @property
    def deck(self) -> Deck:
        if not hasattr(self, '_deck_cache'):
            try:
                object.__setattr__(self, '_deck_cache', Deck.objects.get(id=self.deck_id))
            except Deck.DoesNotExist:
                raise HttpError(404, f"Deck with ID {self.deck_id} not found")
        return self._deck_cache


class GetSummaryDeckOut(Schema):
    id: UUID = Field(..., description="The unique identifier of the deck")
    name: str = Field(..., description="The name of the deck")
    short_summary: str | None = Field(None, description="A short summary of the deck generated by an LLM")
    set_codes: list[str] = Field(default_factory=list, description="The set codes of the cards in the deck")
    date_updated: str = Field(..., description="The date and time when the deck was last updated, in ISO 8601 format")
    creation_status: DeckBuildStatus | None = Field(
        None, description="The status of the deck creation process, if the deck is still being constructed"
    )

    @field_validator('id', mode='before')
    @classmethod
    def validate_id(cls, value: UUID) -> UUID:
        if not Deck.objects.filter(id=value).exists():
            raise RuntimeError('Deck not found')
        return value


class GetFullDeckOut(Schema):
    id: UUID = Field(..., description="The unique identifier of the deck")
    name: str = Field(..., description="The name of the deck")
    short_summary: str | None = Field(None, description="A short summary of the deck generated by an LLM")
    full_summary: str | None = Field(None, description="A full summary of the deck generated by an LLM")
    set_codes: list[str] = Field(default_factory=list, description="The set codes of the cards in the deck")
    date_updated: str = Field(..., description="The date and time when the deck was last updated, in ISO 8601 format")
    cards: list[tuple[int, CardInfo]] = Field(
        default_factory=list,
        description="A list of tuples, where each tuple contains the quantity and the CardInfo of a card in the deck",
    )
    creation_status: DeckBuildStatus | None = Field(
        None, description="The status of the deck creation process, if the deck is still being constructed"
    )

    @field_validator('id', mode='before')
    @classmethod
    def validate_id(cls, value: UUID) -> UUID:
        if not Deck.objects.filter(id=value).exists():
            raise RuntimeError('Deck not found')
        return value

    @field_validator('cards', mode='before')
    @classmethod
    def validate_cards(cls, value: list[tuple[int, CardInfo]]) -> list[tuple[int, CardInfo]]:
        card_ids = set()
        for quantity, card_info in value:
            if quantity < 1:
                raise RuntimeError('Invalid card quantity')
            card_ids.add(card_info.id)

        if not Card.objects.filter(id__in=card_ids).count() == len(card_ids):
            raise RuntimeError('One or more cards not found')
        return value
